### ISSUE TITLE
 Compile Cache basically useless

### ISSUE THREAD

**Issue by Announcement** [atom/timecop#18]
Normally, if you switch themes, the stylesheets need to be regenerated, reload and they're not re-generated. Okay, cool.

Uninstall/disable/update some packages and every reload takes the same amount of rebuilds and the *start time increases*.

Without a detailed view, or tooltip, or something, this is now impossible to debug...

**Comment by thomasjo** [comment]
Since this seems to only be feedback and not something that is actionable, I'm closing this issue.

If there's something you'd like to see fixed or changed, feel free to re-open this issue with details on what behavior you expected as opposed to observed behavior.

---
["How Do I Submit A (Good) Bug Report?"](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report)
